name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push: #nombre de 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository #Nos colocamos ena la rama en la que ocurre el checkout, si no existe la crea
        uses: actions/checkout@v4

      - name: Set up Docker Buildx #Construye el contenedor a partir de la informaci칩n del dockerfile del repositorio
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub #Tarea que inicia sesi칩n en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image #Construye la imagen y realiza un push
        uses: docker/build-push-action@v5
        with:
          context: ./ejercicio-2 #Indicamos el directorio donde el daemon de Docker tratar치 de construir la imagen. 
          file: ./ejercicio-2/Dockerfile #Dentro del contexto, le indicamos el fichero a utilizar para construir la imagen.
          #IMPORTANTE: todos los ficheros que utilice Dockerfile, deben tener su ruta puesta en relaci칩n al mismo.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/containervs:latest
