name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push: #nombre de 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository #Me mueve a la rama en la que ocurre el checkout, si no existe la crea
        uses: actions/checkout@v4

      - name: Set up Docker Buildx #Construye el contenedor a partir de la información del dockerfile del repositorio
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub #Tarea que inicia sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image #Construye la imagen y realiza un push
        uses: docker/build-push-action@v5
        with:
          context: ./ejercicio-2
          file: ./ejercicio-2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/containervs:latest
